"""
Formal ontology schema for regulatory/legal documents.

Entity types and relationship types aligned with legal hierarchy and traceability.
"""

from enum import Enum
from typing import Final


class EntityType(str, Enum):
    """Node types in the regulatory document ontology."""

    REGULATOR = "Regulator"
    ACT = "Act"
    AMENDMENT = "Amendment"
    PART = "Part"
    CHAPTER = "Chapter"
    ARTICLE = "Article"
    SECTION = "Section"
    SUBSECTION = "Subsection"
    CLAUSE = "Clause"
    LEGAL_DEFINITION = "LegalDefinition"
    EXPLANATION = "Explanation"
    PROVISO = "Proviso"
    SCHEDULE = "Schedule"
    ANNEX = "Annex"
    CROSS_REFERENCE = "CrossReference"
    EFFECTIVE_DATE = "EffectiveDate"
    SOURCE_DOCUMENT = "SourceDocument"


class RelationType(str, Enum):
    """Relationship types in the regulatory document ontology."""

    ACT_HAS_CHAPTER = "ACT_HAS_CHAPTER"
    ACT_HAS_SECTION = "ACT_HAS_SECTION"
    CHAPTER_HAS_SECTION = "CHAPTER_HAS_SECTION"
    SECTION_HAS_SUBSECTION = "SECTION_HAS_SUBSECTION"
    SECTION_HAS_CLAUSE = "SECTION_HAS_CLAUSE"
    SUBSECTION_HAS_CLAUSE = "SUBSECTION_HAS_CLAUSE"
    CLAUSE_HAS_SUBCLAUSE = "CLAUSE_HAS_SUBCLAUSE"
    SECTION_HAS_EXPLANATION = "SECTION_HAS_EXPLANATION"
    SECTION_HAS_PROVISO = "SECTION_HAS_PROVISO"
    ACT_HAS_SCHEDULE = "ACT_HAS_SCHEDULE"
    SECTION_CONTAINS_DEFINITION = "SECTION_CONTAINS_DEFINITION"
    DOCUMENT_HAS_PREAMBLE = "DOCUMENT_HAS_PREAMBLE"
    DOCUMENT_HAS_RECITAL = "DOCUMENT_HAS_RECITAL"
    DOCUMENT_HAS_PART = "DOCUMENT_HAS_PART"
    DOCUMENT_HAS_ARTICLE = "DOCUMENT_HAS_ARTICLE"
    DOCUMENT_HAS_SCHEDULE = "DOCUMENT_HAS_SCHEDULE"
    DOCUMENT_HAS_ANNEX = "DOCUMENT_HAS_ANNEX"
    PART_HAS_CHAPTER = "PART_HAS_CHAPTER"
    PART_HAS_ARTICLE = "PART_HAS_ARTICLE"
    SECTION_HAS_PARAGRAPH = "SECTION_HAS_PARAGRAPH"
    PARAGRAPH_HAS_POINT = "PARAGRAPH_HAS_POINT"
    POINT_HAS_SUBPOINT = "POINT_HAS_SUBPOINT"
    CHAPTER_HAS_ARTICLE = "CHAPTER_HAS_ARTICLE"
    SCHEDULE_HAS_SECTION = "SCHEDULE_HAS_SECTION"
    SCHEDULE_HAS_CHAPTER = "SCHEDULE_HAS_CHAPTER"
    SCHEDULE_HAS_ARTICLE = "SCHEDULE_HAS_ARTICLE"
    SCHEDULE_HAS_PARAGRAPH = "SCHEDULE_HAS_PARAGRAPH"
    ANNEX_HAS_SECTION = "ANNEX_HAS_SECTION"
    ANNEX_HAS_CHAPTER = "ANNEX_HAS_CHAPTER"
    ANNEX_HAS_ARTICLE = "ANNEX_HAS_ARTICLE"
    ACT_ISSUED_BY_REGULATOR = "ACT_ISSUED_BY_REGULATOR"
    AMENDS_ACT = "AMENDS_ACT"
    ACT_HAS_EFFECTIVE_DATE = "ACT_HAS_EFFECTIVE_DATE"
    SECTION_HAS_EFFECTIVE_DATE = "SECTION_HAS_EFFECTIVE_DATE"
    CLAUSE_REFERENCES_SECTION = "CLAUSE_REFERENCES_SECTION"
    CLAUSE_REFERENCES_ACT = "CLAUSE_REFERENCES_ACT"
    SECTION_REFERENCES_SECTION = "SECTION_REFERENCES_SECTION"
    SECTION_REFERENCES_ACT = "SECTION_REFERENCES_ACT"
    ACT_SOURCE_DOCUMENT = "ACT_SOURCE_DOCUMENT"
    SECTION_SOURCE_PAGE = "SECTION_SOURCE_PAGE"
    CONTAINS = "CONTAINS"


# Semantic roles for chunks (for filtering and retrieval)
SEMANTIC_ROLES: Final[tuple[str, ...]] = (
    "definition",
    "obligation",
    "prohibition",
    "penalty",
    "exception",
    "proviso",
    "explanation",
    "procedure",
    "authority",
    "schedule",
    "other",
)
